/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desenvolver60.modulos;

import java.awt.Color;
import com.mycompany.desenvolver60.Modulos;

/**
 *
 * @author steph
 */
public class Modulo1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modulo1.class.getName());

    /**
     * Creates new form Modulo1
     */
    public Modulo1() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(244, 232, 184));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JbtnProx1_1 = new javax.swing.JButton();
        JbtnAnt1_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 232, 184));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DESENVOLVER.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JbtnProx1_1.setBorderPainted(false);
        JbtnProx1_1.setContentAreaFilled(false);
        JbtnProx1_1.addActionListener(this::JbtnProx1_1ActionPerformed);
        getContentPane().add(JbtnProx1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 380, 50));

        JbtnAnt1_1.setText("jButton1");
        JbtnAnt1_1.setBorder(null);
        JbtnAnt1_1.setContentAreaFilled(false);
        JbtnAnt1_1.addActionListener(this::JbtnAnt1_1ActionPerformed);
        getContentPane().add(JbtnAnt1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 30, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnProx1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnProx1_1ActionPerformed
        setVisible(false);
        Modulo1_2 janela = new Modulo1_2();
        janela.setVisible(true);
    }//GEN-LAST:event_JbtnProx1_1ActionPerformed

    private void JbtnAnt1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAnt1_1ActionPerformed
        setVisible(false);
        Modulos janela = new Modulos();
        janela.setVisible(true);
    }//GEN-LAST:event_JbtnAnt1_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modulo1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnAnt1_1;
    private javax.swing.JButton JbtnProx1_1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
