package com.mycompany.desenvolver60.modulos;

import java.awt.Color;


public class Modulo1_2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modulo1_2.class.getName());

    
    public Modulo1_2() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(244, 232, 184));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbtnProx1_2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JbtnAnt1_2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnProx1_2.setBackground(new java.awt.Color(242, 242, 242));
        JbtnProx1_2.setBorder(null);
        JbtnProx1_2.setBorderPainted(false);
        JbtnProx1_2.setContentAreaFilled(false);
        JbtnProx1_2.addActionListener(this::JbtnProx1_2ActionPerformed);
        getContentPane().add(JbtnProx1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, 380, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DESENVOLVER (1.2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 549, -1));

        JbtnAnt1_2.setText("jButton1");
        JbtnAnt1_2.setBorder(null);
        JbtnAnt1_2.setContentAreaFilled(false);
        JbtnAnt1_2.addActionListener(this::JbtnAnt1_2ActionPerformed);
        getContentPane().add(JbtnAnt1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 30, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnProx1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnProx1_2ActionPerformed
        setVisible(false);
        Modulo1_3 janela = new Modulo1_3();
        janela.setVisible(true);
    }//GEN-LAST:event_JbtnProx1_2ActionPerformed

    private void JbtnAnt1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAnt1_2ActionPerformed
        setVisible(false);
        Modulo1 janela = new Modulo1();
        janela.setVisible(true);
    }//GEN-LAST:event_JbtnAnt1_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modulo1_2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnAnt1_2;
    private javax.swing.JButton JbtnProx1_2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
