package com.mycompany.desenvolver60;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;


public class CriarConta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarConta.class.getName());
    private boolean senhaVisivel = false;

    public CriarConta() {

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        getContentPane().setBackground(new Color(244, 232, 184));
        jLabelC.setFont(FonteUtil.carregarFonte("AbrilFatface-Regular.ttf", 30f));
        label22.setFont(FonteUtil.carregarFonte("league-spartan-bold.otf", 15f).deriveFont(Font.BOLD));
        label22.setText("<html><u>Preencha com seus dados</u></html>");
    }

    private boolean verificarEmail(String email) {

        String sql = "SELECT id FROM dadosCadastro WHERE email = ?";

        try (
                Connection conexao = Conexao.conectar(); PreparedStatement stmt = conexao.prepareStatement(sql);) {
            stmt.setString(1, email);
            ResultSet resultado = stmt.executeQuery();
            return resultado.next();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao verificar o e-mail.");
            return true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        roundedPanel1 = new com.mycompany.desenvolver60.RoundedPanel();
        jLabelC = new javax.swing.JLabel();
        label22 = new javax.swing.JLabel();
        cadastroBnt = new com.mycompany.desenvolver60.RoundedButton();
        textSenha = new javax.swing.JPasswordField();
        textNome = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        btnVerSenha = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setPreferredSize(new java.awt.Dimension(549, 765));

        jPanel2.setBackground(new java.awt.Color(106, 195, 198));
        jPanel2.setForeground(new java.awt.Color(106, 195, 198));

        btnMenu.setBackground(new java.awt.Color(106, 195, 198));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome (4) (2) (1).png"))); // NOI18N

        roundedPanel1.setBackground(new java.awt.Color(106, 195, 198));

        jLabelC.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC.setText("Crie Sua Conta");

        label22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label22.setForeground(new java.awt.Color(20, 82, 84));
        label22.setText("Preencha com seus dados");

        cadastroBnt.setBackground(new java.awt.Color(246, 211, 71));
        cadastroBnt.setBorder(null);
        cadastroBnt.setForeground(new java.awt.Color(20, 82, 84));
        cadastroBnt.setText("Cadastrar");
        cadastroBnt.setToolTipText("Clique aqui para iniciar as atividades");
        cadastroBnt.setBorderPainted(true);
        cadastroBnt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cadastroBnt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastroBnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroBntMouseClicked(evt);
            }
        });
        cadastroBnt.addActionListener(this::cadastroBntActionPerformed);

        textSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        textSenha.addActionListener(this::textSenhaActionPerformed);

        textNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        textNome.addActionListener(this::textNomeActionPerformed);

        textEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));
        textEmail.setName(""); // NOI18N
        textEmail.addActionListener(this::textEmailActionPerformed);

        btnVerSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visibility_16dp_000000_FILL0_wght400_GRAD0_opsz20 (1)_1.png"))); // NOI18N
        btnVerSenha.addActionListener(this::btnVerSenhaActionPerformed);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(textNome)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(textSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(cadastroBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundedPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textEmail, textNome, textSenha});

        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label22)
                .addGap(34, 34, 34)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(cadastroBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

    }//GEN-LAST:event_btnMenuActionPerformed

    private void cadastroBntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroBntMouseClicked

    }//GEN-LAST:event_cadastroBntMouseClicked

    private void cadastroBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBntActionPerformed
    String nome = textNome.getText().trim();
    String email = textEmail.getText().trim();
    String senha = new String(textSenha.getPassword()).trim();

    if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Nem todos os campos foram preenchidos"
        );

        return;
    }

    if (!email.contains("@") || !email.contains(".")) {

        JOptionPane.showMessageDialog(
                this,
                "O e-mail informado é inválido"
        );

        return;
    }

    if (verificarEmail(email)) {

        JOptionPane.showMessageDialog(
                this,
                "E-mail já cadastrado"
        );

        return;
    }

    String codigo = CodigoVerificacao.gerarCodigo();

    try {

        EnviarEmail.enviarCodigo(email, codigo);

        VerificarEmail janela = new VerificarEmail(
                nome,
                email,
                senha,
                codigo
        );

        janela.setVisible(true);
        this.dispose();

    } catch (Exception e) {

        e.printStackTrace();

        JOptionPane.showMessageDialog(
                this,
                "Não foi possível enviar o código de verificação."
        );
    }
    }//GEN-LAST:event_cadastroBntActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void btnVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSenhaActionPerformed

        if (senhaVisivel) {
            textSenha.setEchoChar('•');
            senhaVisivel = false;
        } else {
            textSenha.setEchoChar((char) 0);
            senhaVisivel = true;
        }
    }//GEN-LAST:event_btnVerSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CriarConta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnVerSenha;
    private com.mycompany.desenvolver60.RoundedButton cadastroBnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label22;
    private com.mycompany.desenvolver60.RoundedPanel roundedPanel1;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}
