
package com.mycompany.desenvolver60;

import java.awt.Color;
import com.mycompany.desenvolver60.modulos.Modulo1;

public class Modulos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modulos.class.getName());

    /**
     * Creates new form Modulos
     */
    public Modulos() {
        initComponents();
        jScrollPane1.setVerticalScrollBarPolicy(
        javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS
    );
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(244,232,184));
        jScrollPane1.setBackground(new Color(244,232,184));
        jPanel1.setBackground(new Color(244,232,184));
        labelBV.setText("<html>Bem-Vindo(a) ao <br> Desenvolver60+ </br> </html");
        labelFF.setFont(FonteUtil.carregarFonte("LeagueSpartan-VariableFont_wght.ttf", 16f));
        labelVa.setFont(FonteUtil.carregarFonte("LeagueSpartan-VariableFont_wght.ttf", 16f));
        labelFI.setFont(FonteUtil.carregarFonte("LeagueSpartan-VariableFont_wght.ttf", 16f));
        labelFI.setText("<html><b>FICAMOS FELIZES POR TER VOCÊ AQUI!</b></html>");
        labelFF.setText("<html><b> ESTA APLICAÇÃO FOI FEITA PARA </b><b>AJUDAR VOCÊ A USAR A</b><b>TECNOLOGIA DE FORMA SIMPLES, NO </b><b>SEU TEMPO E SEM MEDO DE ERRAR.</b></html>");
        labelVa.setText("<html><b>VAMOS CAMINHAR JUNTOS,</b> <b>PASSO A PASSO, PARA QUE</b><b>VOCÊ SE SINTA CADA VEZ</b><b>MAIS CONFIANTE E SEGURO(A) NO MUNDO DIGITAL.</b></html>");
        btnM1.setFont(FonteUtil.carregarFonte("LeagueSpartan-VariableFont_wght.ttf", 16f));
        btnM1.setText("<html><b>MÓDULO: CADASTRO EM SISTEMAS</b></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnAudio = new javax.swing.JButton();
        labelBV = new javax.swing.JLabel();
        labelFF = new javax.swing.JLabel();
        labelVa = new javax.swing.JLabel();
        labelFI = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnM1 = new com.mycompany.desenvolver60.RoundedButton();
        btnM2 = new com.mycompany.desenvolver60.RoundedButton();
        btnM5 = new com.mycompany.desenvolver60.RoundedButton();
        btnM6 = new com.mycompany.desenvolver60.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(549, 765));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(106, 195, 198));
        jPanel2.setForeground(new java.awt.Color(106, 195, 198));

        btnMenu.setBackground(new java.awt.Color(106, 195, 198));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        btnAudio.setBackground(new java.awt.Color(0, 204, 204));
        btnAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select_to_speak_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnAudio.setToolTipText("Ler a página");
        btnAudio.setBorder(null);
        btnAudio.setBorderPainted(false);
        btnAudio.setContentAreaFilled(false);
        btnAudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAudio.setFocusPainted(false);
        btnAudio.addActionListener(this::btnAudioActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 549, -1));

        labelBV.setFont(new java.awt.Font("Abril Fatface", 0, 40)); // NOI18N
        labelBV.setForeground(new java.awt.Color(20, 82, 84));
        labelBV.setText("Bem-Vindo(a) ao Desenvolver60+");
        getContentPane().add(labelBV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 410, 120));

        labelFF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFF.setText("FICAMOS FELIZES POR TER VOCê AQUI!");
        getContentPane().add(labelFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 400, 120));

        labelVa.setText("VAMOS");
        getContentPane().add(labelVa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 340, 80));

        labelFI.setText("Ficamos");
        getContentPane().add(labelFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 340, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 200));

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnM1.setBackground(new java.awt.Color(246, 211, 71));
        btnM1.setForeground(new java.awt.Color(20, 82, 84));
        btnM1.setText("MÓDULO: USO BÁSICOS EM APLICAÇÕES");
        btnM1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnM1.addActionListener(this::btnM1ActionPerformed);
        jPanel1.add(btnM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 345, 34));

        btnM2.setBackground(new java.awt.Color(246, 211, 71));
        btnM2.setForeground(new java.awt.Color(20, 82, 84));
        btnM2.setText("MÓDULO: CADASTRO EM SISTEMAS");
        btnM2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnM2.addActionListener(this::btnM2ActionPerformed);
        jPanel1.add(btnM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 360, 40));

        btnM5.setBackground(new java.awt.Color(246, 211, 71));
        btnM5.setForeground(new java.awt.Color(20, 82, 84));
        btnM5.setText("MÓDULO: USO BÁSICOS EM APLICAÇÕES");
        btnM5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnM5.addActionListener(this::btnM5ActionPerformed);
        jPanel1.add(btnM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 345, 34));

        btnM6.setBackground(new java.awt.Color(246, 211, 71));
        btnM6.setForeground(new java.awt.Color(20, 82, 84));
        btnM6.setText("MÓDULO: CADASTRO EM SISTEMAS");
        btnM6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnM6.addActionListener(this::btnM6ActionPerformed);
        jPanel1.add(btnM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 360, 40));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 530, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudioActionPerformed
        
    }//GEN-LAST:event_btnAudioActionPerformed

    private void btnM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM5ActionPerformed

    private void btnM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM2ActionPerformed

    private void btnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM1ActionPerformed

    private void btnM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM6ActionPerformed
       setVisible(false);
       Modulo1 janela = new Modulo1();
       janela.setVisible(true);
    }//GEN-LAST:event_btnM6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modulos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudio;
    private com.mycompany.desenvolver60.RoundedButton btnM1;
    private com.mycompany.desenvolver60.RoundedButton btnM2;
    private com.mycompany.desenvolver60.RoundedButton btnM5;
    private com.mycompany.desenvolver60.RoundedButton btnM6;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBV;
    private javax.swing.JLabel labelFF;
    private javax.swing.JLabel labelFI;
    private javax.swing.JLabel labelVa;
    // End of variables declaration//GEN-END:variables
}
