
package com.mycompany.desenvolver60;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author steph
 */
public class VerificarEmail extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerificarEmail.class.getName());

        private String nome;
        private String email;
        private String senha;
        private String codigoCorreto;

         public VerificarEmail(String nome, String email, String senha, String codigo) {

        initComponents();

        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.codigoCorreto = codigo;

        setLocationRelativeTo(null);
        setResizable(false);

        getContentPane().setBackground(
                new Color(244, 232, 184)
        );
    }
    
    private boolean cadastrarUsuario(){
        String sql = """
        INSERT INTO dadosCadastro
        (nome, email, senha, verificado)
        VALUES (?, ?, ?, ?)
        """;

    try (
        Connection conexao = Conexao.conectar();
        PreparedStatement stmt = conexao.prepareStatement(sql)
    ) {

        stmt.setString(1, nome);
        stmt.setString(2, email);
        stmt.setString(3, senha);
        stmt.setInt(4, 1);

        stmt.executeUpdate();

        return true;

    } catch (SQLException e) {

        e.printStackTrace();

        JOptionPane.showMessageDialog(
                this,
                "Erro ao realizar o cadastro."
        );

        return false;
    }
    
    }     


        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.mycompany.desenvolver60.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        labelE = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cadastroBnt = new com.mycompany.desenvolver60.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Abril Fatface", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verifique seu E-mail");

        labelE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelE.setForeground(new java.awt.Color(20, 82, 84));
        labelE.setText("Enviamos um código para seu e-mail");

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        cadastroBnt.setBackground(new java.awt.Color(246, 211, 71));
        cadastroBnt.setBorder(null);
        cadastroBnt.setForeground(new java.awt.Color(20, 82, 84));
        cadastroBnt.setText("Verificar");
        cadastroBnt.setToolTipText("Clique aqui para iniciar as atividades");
        cadastroBnt.setBorderPainted(true);
        cadastroBnt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cadastroBnt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastroBnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroBntMouseClicked(evt);
            }
        });
        cadastroBnt.addActionListener(this::cadastroBntActionPerformed);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelE, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(cadastroBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelE)
                .addGap(33, 33, 33)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked

    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        String codigoDigitado =
                txtCodigo.getText().trim();

        if (codigoDigitado.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Digite o código de verificação."
            );

            return;
        }

        if (codigoDigitado.equals(codigoCorreto)) {

            JOptionPane.showMessageDialog(
                    this,
                    "E-mail verificado com sucesso!"
            );

            //  colocaremos aqui o cadastro no banco.

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Código incorreto."
            );
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void cadastroBntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroBntMouseClicked

    }//GEN-LAST:event_cadastroBntMouseClicked

    private void cadastroBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBntActionPerformed
    String codigo = CodigoVerificacao.gerarCodigo();

    try {

        EnviarEmail.enviarCodigo(email, codigo);

        VerificarEmail janela = new VerificarEmail(
                nome,
                email,
                senha, codigo);

        janela.setVisible(true);
        this.dispose();

    } catch (Exception e) {

        e.printStackTrace();

        JOptionPane.showMessageDialog(
                this,
                "Não foi possível enviar o código de verificação."
        );
    }
    }//GEN-LAST:event_cadastroBntActionPerformed
    

    
    public static void main(String args[]) {
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.desenvolver60.RoundedButton cadastroBnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelE;
    private RoundedPanel roundedPanel1;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
